int openDisplay(void);
void grab(char** keys, int* buttons);
void resize(int window, int left, int top, int width, int height);
void resizeKeyWindow(int left, int top, int width, int height);
void raise(int window);
void getAttr(int window);
void nextEvent(void);
int isKeyPress(void);
int isButtonPress(void);
int isMotionNotify(void);
int isButtonRelease(void);
int getWindowForKeyEvent(void);
int getWindowForButtonEvent(void);
int getButton(void);
int getXRoot(void);
int getYRoot(void);
int isKey(char* key);
