int openDisplay(void);
void grab(char** keys, int* buttons);
void resize(int window, int left, int top, int width, int height);
void raise(int window);
void handleMotion(void* evp);
void getAttr(int window);
void setStarted(int started);
void setStart(void* evp);
int isStarted(void);
void nextEvent(void* evp);
